name: package apisix-runtime rpm for el8

on:
  push:
    branches: [ master ]
    tags:
      - "v*"
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '*.md'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      BUILD_APISIX_RUNTIME_VERSION: 1.0.1
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get install -y make ruby ruby-dev rubygems build-essential

      - name: build apisix-runtime rpm
        run: |
          make package type=rpm app=apisix-runtime runtime_version=${BUILD_APISIX_RUNTIME_VERSION} image_base=centos image_tag=8

      - name: run centos8 docker and mapping apisix-runtime rpm into container
        run: |
          docker run -itd -v /home/runner/work/apisix-build-tools/apisix-build-tools/output:/output --name centos8Instance --net="host" docker.io/centos:8 /bin/bash

      - name: install dependencies in container
        run: |
          docker exec centos8Instance bash -c "sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*"
          docker exec centos8Instance bash -c "sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*"
          docker exec centos8Instance bash -c "dnf install -y centos-release-stream"
          docker exec centos8Instance bash -c "dnf swap -y centos-{linux,stream}-repos"
          docker exec centos8Instance bash -c "dnf distro-sync -y"
          docker exec centos8Instance bash -c "dnf install -y yum-utils"

      - name: install rpm in container
        run: |
          docker exec centos8Instance bash -c "yum -y localinstall /output/apisix-runtime-${BUILD_APISIX_RUNTIME_VERSION}-0.el8.x86_64.rpm"

      - name: check and ensure apisix-runtime is installed
        run: |
          docker exec centos8Instance bash -c "/usr/local/openresty/bin/etcdctl -h" || exit 1
          export APISIX_RUNTIME_VER=$(docker exec centos8Instance bash -c "openresty -V" 2>&1 | awk '/-O2 -DAPISIX_RUNTIME_VER=/{print $5}' | awk -v FS="=" '{print $2}')
          if [ "$APISIX_RUNTIME_VER" != "${BUILD_APISIX_RUNTIME_VERSION}" ]; then exit 1; fi

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: apisix-runtime-${{ env.BUILD_APISIX_RUNTIME_VERSION }}-0.el8.x86_64.rpm
          path: output/apisix-runtime-${{ env.BUILD_APISIX_RUNTIME_VERSION }}-0.el8.x86_64.rpm
          retention-days: 5
          if-no-files-found: error
