name: package apisix-openresty rpm for el7

on:
  push:
    branches: 
      - master
      - upload-artifact
    tags:
      - "v*"
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_APISIX_OR_VERSION: 1.19.3.2.0
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get install -y make ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm
          sudo apt-get install -y rpm

      - name: build apisix-openresty rpm
        run: |
          make package type=rpm app=apisix-openresty version=${BUILD_APISIX_OR_VERSION} image_base=centos image_tag=7

      - name: run centos7 docker and mapping apisix-openresty rpm into container
        run: |
          docker run -itd -v /home/runner/work/apisix-build-tools/apisix-build-tools/output:/output --name centos7Instance --net="host" docker.io/centos:7 /bin/bash

      - name: install dependencies in container
        run: |
          docker exec centos7Instance bash -c "yum-config-manager --add-repo https://openresty.org/package/centos/openresty.repo"
          docker exec centos7Instance bash -c "yum -y install openresty-openssl111 openresty-pcre openresty-zlib"

      - name: install rpm in container
        run: |
          docker exec centos7Instance bash -c "yum -y localinstall /output/apisix-openresty-${BUILD_APISIX_OR_VERSION}-0.el7.x86_64.rpm"

      - name: check and ensure openresty is installed
        run: |
          export APISIX_OPENRESTY_VER=$(docker exec centos7Instance bash -c "openresty -V" 2>&1 | awk '/-O2 -DAPISIX_OPENRESTY_VER=/{print $5}' | awk -v FS="=" '{print $2}')
          if [ "$APISIX_OPENRESTY_VER" != "${BUILD_APISIX_OR_VERSION}" ]; then exit 1; fi

      - name: upload artifact
        uses: actions/upload-artifact@v2.2.2
        if: ${{ github.event_name == 'push'   }}
        with:
          name: apisix-openresty.rpm
          path: |
            /home/runner/work/apisix-build-tools/apisix-build-tools/output/apisix-openresty-1.19.3.2.0-0.el7.x86_64.rpm
          retention-days: 7
