name: package apisix-base apk

on:
  push:
    branches: [ openresty/* ]
    tags:
      - "v*"
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      BUILD_APISIX_BASE_VERSION: 1.21.4.1.3
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get install -y make ruby ruby-dev rubygems build-essential

      - name: build apisix-base apk
        run: |
          make package version=${BUILD_APISIX_BASE_VERSION} image_base=alpine image_tag=3.15 app=apisix-base type=apk

      - name: Run apisix-base image
        run: |
          docker run -itd  --name apisix.base  apache/apisix-base-apk:${BUILD_APISIX_BASE_VERSION}

      - name: Check and Ensure luarocks is installed
        run: |
          export LUA_ROCKS=$(docker exec apisix.base bash -c "luarocks --version" 2>&1 )
          if [ "$LUA_ROCKS" == "bash: luarocks: command not found" ]; then exit 1; fi
