name: package apisix rpm for el7

on:
  push:
    branches: [ master , openssl3]
    tags:
      - "v*"
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master , openssl3]
    paths-ignore:
      - '*.md'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      etcd:
        image: bitnami/etcd:3.4.0
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ALLOW_NONE_AUTHENTICATION: yes
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get install -y make ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm
          sudo apt-get install -y rpm

      # - name: packaging APISIX(-remote) with remote code
      #   run: |
      #     make package type=rpm app=apisix version=master checkout=revolyssup/openssl3 image_base=centos image_tag=7 artifact=apisix-remote

      - name: packaging APISIX(-local) with local code
        run: |
          git clone https://github.com/apache/apisix.git
          make package type=rpm app=apisix version=master checkout=revolyssup/openssl3 image_base=centos image_tag=7 local_code_path=./apisix artifact=apisix-local

      - name: install apisix rpm into container
        run: |
          docker build -t apache/apisix:master-rpm-test --build-arg APISIX_VERSION=master -f test/apisix/Dockerfile.test.apisix.rpm.el7 .

      # - name: enable apisix repository in container
      #   run: 
      #     docker exec centos7Instance bash -c "rpm --import https://repos.apiseven.com/KEYS"
      #     docker exec centos7Instance bash -c "yum -y install https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm"

      # - name: install APISIX(-remote) master by rpm in container
      #   run: |
      #     docker exec centos7Instance bash -c "yum -y localinstall /output/apisix-remote-master-0.el7.x86_64.rpm"
      #     docker exec centos7Instance bash -c "apisix start"

      # - name: check and ensure APISIX(-remote) master is installed
      #   run: |
      #     code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1')
      #     if [ ! $code -eq 200 ]; then
      #         echo "failed: failed to install Apache APISIX by rpm"
      #         exit 1
      #     fi

      # - name: stop and uninstall APISIX(-remote) master
      #   run: |
      #     docker exec centos7Instance bash -c "pkill -f nginx"
      #     docker exec centos7Instance bash -c "yum -y erase apisix-remote-master"

      # - name: install APISIX(-local) by rpm in container
      #   run: |
      #     docker exec centos7Instance bash -c "yum -y localinstall /output/apisix-local-master-0.el7.x86_64.rpm"
      #     docker exec centos7Instance bash -c "apisix start"

      - name: check and ensure APISIX(-local) is installed
        run: |
          docker run -d --rm --name apache/apisix:master-rpm-test -v $(pwd)/test/apisix/config.yaml:/usr/local/apisix/conf/config.yaml -p 9180:9180 -p 9080:9080 -p 9443:9443 apache/apisix:${PACKAGE_APISIX_VERSION}-rpm-test
          sleep 20
          code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1')
          if [ ! $code -eq 200 ]; then
              echo "failed: failed to install Apache APISIX by rpm"
              exit 1
          fi
